### ISSUE TITLE
errorr while attempting connection using key

### ISSUE THREAD

**Issue by ghost** [cleverwise/connect2ssh#1]
As far as I can see, connect2ssh works fine when connecting with uid/passwd.
When I try to connect through ssh key, though, the following error message occurs:

**Key file ~/.ssh/id_rsa.pub does NOT exist!**

However, the following command:
_file ~/.ssh/id_rsa.pub_
tells me it does exist: 
_OpenSSH RSA public key_

**Comment by cleverwise** [comment]
That can happen on some systems and it is simple to fix.  I really should alter the code to address that and will in the next version (2.0).  I'll try and push that out today or tomorrow (2.0).

At any rate you may fix that for now:

shell_prompt> connect2ssh config-update key_path

Now enter the full path to your key directory (excluding trailing slash).  Example below is showing a username of joe and keys stored in .ssh

/home/joe/.ssh

Then try again to connect and it should work. :-)

**Comment by ghost** [comment]
Works fine now. Thanks for the quick response / solution!
